---
AWSTemplateFormatVersion : "2010-09-09"
Parameters:
  Subnet1:
    Type: String
    Description: local subnet
    Default: subnet-a293d3f8
  Subnet2:
    Type: String
    Description: local subnet
    Default: subnet-1efee856
  Subnet3:
    Type: String
    Description: local subnet
    Default: subnet-07404661
  VPCID:
    Description: VPC ID
    Type: String
    Default: vpc-10c51069
Resources:
  jcILU2EFSmountSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh to client host
      GroupName: jcILU2EFSmountSG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: EFSmountSG
  jcILU2EFS:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: DISABLED
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: jcILU2EFS
  jcILU2EFSMT1:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref jcILU2EFS
      SecurityGroups: 
        - !GetAtt jcILU2EFSmountSG.GroupId
      SubnetId: !Ref Subnet1
  jcILU2EFSMT2:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref jcILU2EFS
      SecurityGroups: 
        - !GetAtt jcILU2EFSmountSG.GroupId
      SubnetId: !Ref Subnet2
  jcILU2EFSMT3:
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref jcILU2EFS
      SecurityGroups: 
        - !GetAtt jcILU2EFSmountSG.GroupId
      SubnetId: !Ref Subnet3