---
AWSTemplateFormatVersion : "2010-09-09"
Parameters:
  Subnet1:
    Type: String
    Description: local subnet
    Default: subnet-a293d3f8
  Subnet2:
    Type: String
    Description: local subnet
    Default: subnet-1efee856
  Subnet3:
    Type: String
    Description: local subnet
    Default: subnet-07404661
  VPCID:
    Description: VPC ID
    Type: String
    Default: vpc-10c51069
Resources:
  jcILU2WPInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow instance access to EFS and RDS
      GroupName: jcILU2WPInstanceSG
      Tags:
        - Key: Name
          Value: jcILU2WPInstanceSG
  jcILU2RDSSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow RDS access
      SecurityGroupIngress:
        IpProtocol: tcp
        SourceSecurityGroupName: !Ref jcILU2WPInstanceSG
        FromPort: 3306
        ToPort: 3306
      VpcId: !Ref VPCID
      Tags:
        - Key: Name
          Value: jcILU2RDSSG
  jcILU2RDSmySQL:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 20
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: jcILU2dbinstance-1
      DBName: jcILU2ApacheDBnamn
      Engine: mysql
      EngineVersion: 8.0.28
      MasterUsername: admin
      MasterUserPassword: adminadmin
      Port: 3306
      PubliclyAccessible: no
      VPCSecurityGroups: 
        - !GetAtt jcILU2RDSSG.GroupId